# This file is used by Acquia Pipelines continuous integration.
version: 1.1.0
services:
  - mysql
  - php:
      version: 7.2

events:
  build:
    steps:
      - setup:
          type: script
          script:
            # Add Composer's local bin directory to the PATH so that we will be
            # running our installed versions of Drush, PHPCS, Behat, etc.
            - export PATH="$HOME/.composer/vendor/bin:$SOURCE_DIR/vendor/bin:$PATH"
            - composer validate --no-check-all --ansi --no-interaction
            - composer install
